# Generated by Django 4.1.7 on 2023-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=255, unique=True),
        ),
    ]
